version: "3"

services:
  django:
    build:
      context: .
    ports:
      - "8080:8080"
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    env_file:
      - env/django.env
    depends_on:
      - postgres
      - elastic_search
    links:
      - postgres
      - redis
      - elastic_search

    stdin_open: true
    tty: true

  postgres:
    image: postgres:12.0-alpine
    volumes:
      - style_icon_data:/var/lib/postgresql/data
    env_file:
      - env/postgres.env
    environment:
      - POSTGRES_USER=style-icon
      - POSTGRES_PASSWORD=style-icon
      - POSTGRES_DB=style-icon

  redis:
    image: redis:6.2-alpine

  elastic_search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: style-icon_elastic_search
    environment:
      - node.name=style-icon_elastic_search
      - cluster.name=style-icon_es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - style_icon_elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  style_icon_data: { }
  style_icon_data_backups: { }
  style_icon_elasticsearch_data: { }
