# Generated by Django 3.2.10 on 2022-01-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='service_period',
            field=models.IntegerField(default=0, help_text='Service Period in Months.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pre_order',
            field=models.BooleanField(default=False, help_text='Can be pre ordered', verbose_name='Is pre-order product'),
        ),
    ]
