# Generated by Django 3.2.10 on 2022-01-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220101_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='service_period',
            field=models.IntegerField(default=0, help_text='Service Period in Months. How long user get free service.', verbose_name='Service Period in Months.'),
        ),
    ]
