# Generated by Django 3.2.10 on 2021-12-31 18:28

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This will be exposed to the outside world.', unique=True, verbose_name='UUID')),
                ('total_amount', models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Total amount of the cart including all costs and VAT.', max_digits=15, verbose_name='Total Amount')),
                ('total_amount_ex_vat', models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Total amount of the cart including all costs(excl. VAT).', max_digits=15, verbose_name='Total Amount(excl. VAT)')),
                ('shipping_address_id', models.PositiveIntegerField(blank=True, help_text='FK to the original shipping address of the customer.', null=True, verbose_name='Shipping Address')),
                ('payment_type', models.CharField(choices=[('none', 'User defined'), ('cash on delivery', 'Cash on delivery'), ('digital', 'Digital')], default='none', help_text='Generic applied payment type. But remember the payment type can differ per line', max_length=50, verbose_name='Generic payment type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Customer who created the cart.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['payment_type'], name='cart_cart_payment_01ed52_idx'),
        ),
    ]
