# Generated by Django 3.2.10 on 2022-01-01 07:30

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This will be exposed to the outside world.', unique=True, verbose_name='UUID')),
                ('product_code', models.CharField(blank=True, help_text='Product code.', max_length=128, null=True, verbose_name='Product Code')),
                ('product_name', models.CharField(blank=True, help_text='Name of product.', max_length=256, null=True, verbose_name='Product Name')),
                ('quantity', models.IntegerField(default=1, help_text='Quantity of product.', verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Price per product. This is the unit price of the product.', max_digits=12, verbose_name='Price')),
                ('price_ex_vat', models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Price(excl. VAT) per product. This is the unit price(excl. VAT) of the product.', max_digits=12, verbose_name='Price(excl. VAT)')),
                ('total_amount', models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Total amount of the line.', max_digits=12, verbose_name='Total Amount')),
                ('total_amount_ex_vat', models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Total amount(excl. VAT) of the line.', max_digits=12, verbose_name='Total Amount(excl. VAT)')),
                ('cart', models.ForeignKey(help_text='To which cart this line belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cart.cart', verbose_name='Cart')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='cartline',
            index=models.Index(fields=['uuid', 'product_code'], name='cart_cartli_uuid_fd4f11_idx'),
        ),
    ]
