# Generated by Django 3.2.10 on 2021-12-21 12:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This will be exposed to the outside world.', unique=True, verbose_name='UUID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='User name')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(blank=True, help_text='User Contact Number', max_length=64, verbose_name='Contact Number')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive user can do nothing in the system.')),
                ('is_pending', models.BooleanField(default=True, help_text='User activity is pending for some reasons.')),
                ('is_staff', models.BooleanField(default=False, help_text='User is a admin user.')),
                ('is_dashboard_user', models.BooleanField(default=False, help_text='User is a dashboard user.')),
                ('is_blocked', models.BooleanField(default=False, help_text='User is blocked by authority for some reasons.')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
