# Generated by Django 3.2.10 on 2021-12-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text='User first name', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, help_text='User last/nick name', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='mid_name',
            field=models.CharField(blank=True, help_text='User middle name', max_length=255),
        ),
    ]
