# Generated by Django 3.2.10 on 2021-12-26 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_user_name', models.CharField(help_text='The email address used for the login attempt.', max_length=254, verbose_name='username')),
                ('used_email', models.CharField(blank=True, help_text='The email address used for the login attempt.', max_length=254, null=True, verbose_name='email')),
                ('is_successful', models.BooleanField(default=True, help_text='True denotes that the login was successful')),
                ('attempted_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='time attempted')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='The IP from which the login was attempted', null=True, verbose_name='IP address')),
                ('browser', models.CharField(blank=True, help_text='The browser used to login', max_length=30, null=True, verbose_name='browser')),
            ],
            options={
                'verbose_name': 'User Login Log',
                'verbose_name_plural': 'User Login Logs',
                'ordering': ('-id',),
            },
        ),
    ]
